#include "input.hpp"

namespace tst
{
	String getKeycodeString(EKeyCode key_code)
	{
		switch (key_code)
		{
			case EKeyCode::eSpace: return "Space";
			case EKeyCode::eApostrophe: return "Apostrophe";
			case EKeyCode::eComma: return "Comma";
			case EKeyCode::eMinus: return "Minus";
			case EKeyCode::ePeriod: return "Period";
			case EKeyCode::eSlash: return "Slash";
			case EKeyCode::e0: return "0";
			case EKeyCode::e1: return "1";
			case EKeyCode::e2: return "2";
			case EKeyCode::e3: return "3";
			case EKeyCode::e4: return "4";
			case EKeyCode::e5: return "5";
			case EKeyCode::e6: return "6";
			case EKeyCode::e7: return "7";
			case EKeyCode::e8: return "8";
			case EKeyCode::e9: return "9";
			case EKeyCode::eSemicolon: return ";";
			case EKeyCode::eEqual: return "=";
			case EKeyCode::eA: return "A";
			case EKeyCode::eB: return "B";
			case EKeyCode::eC: return "C";
			case EKeyCode::eD: return "D";
			case EKeyCode::eE: return "E";
			case EKeyCode::eF: return "F";
			case EKeyCode::eG: return "G";
			case EKeyCode::eH: return "H";
			case EKeyCode::eI: return "I";
			case EKeyCode::eJ: return "J";
			case EKeyCode::eK: return "K";
			case EKeyCode::eL: return "L";
			case EKeyCode::eM: return "M";
			case EKeyCode::eN: return "N";
			case EKeyCode::eO: return "O";
			case EKeyCode::eP: return "P";
			case EKeyCode::eQ: return "Q";
			case EKeyCode::eR: return "R";
			case EKeyCode::eS: return "S";
			case EKeyCode::eT: return "T";
			case EKeyCode::eU: return "U";
			case EKeyCode::eV: return "V";
			case EKeyCode::eW: return "W";
			case EKeyCode::eX: return "X";
			case EKeyCode::eY: return "Y";
			case EKeyCode::eZ: return "Z";
			case EKeyCode::eLeftBracket: return "(";
			case EKeyCode::eBackslash: return "\\";
			case EKeyCode::eRightBracket: return ")";
			case EKeyCode::eGraveAccent: return "`";
			case EKeyCode::eWorld1: return "Win1";
			case EKeyCode::eWorld2: return "Win2";
			case EKeyCode::eEscape: return "Escape";
			case EKeyCode::eEnter: return "Enter";
			case EKeyCode::eTab: return "Tab";
			case EKeyCode::eBackspace: return "Backspace";
			case EKeyCode::eInsert: return "Insert";
			case EKeyCode::eDelete: return "Delete";
			case EKeyCode::eRight: return "Right";
			case EKeyCode::eLeft: return "Left";
			case EKeyCode::eDown: return "Down";
			case EKeyCode::eUp: return "Up";
			case EKeyCode::ePageUp: return "Page Up";
			case EKeyCode::ePageDown: return "Page Down";
			case EKeyCode::eHome: return "Home";
			case EKeyCode::eEnd: return "End";
			case EKeyCode::eCapsLock: return "Caps Lock";
			case EKeyCode::eScrollLock: return "Scroll Lock";
			case EKeyCode::eNumLock: return "Num Lock";
			case EKeyCode::ePrintScreen: return "Print Screen";
			case EKeyCode::ePause: return "Pause";
			case EKeyCode::eF1: return "F1";
			case EKeyCode::eF2: return "F2";
			case EKeyCode::eF3: return "F3";
			case EKeyCode::eF4: return "F4";
			case EKeyCode::eF5: return "F5";
			case EKeyCode::eF6: return "F6";
			case EKeyCode::eF7: return "F7";
			case EKeyCode::eF8: return "F8";
			case EKeyCode::eF9: return "F9";
			case EKeyCode::eF10: return "F10";
			case EKeyCode::eF11: return "F11";
			case EKeyCode::eF12: return "F12";
			case EKeyCode::eF13: return "F13";
			case EKeyCode::eF14: return "F14";
			case EKeyCode::eF15: return "F15";
			case EKeyCode::eF16: return "F16";
			case EKeyCode::eF17: return "F17";
			case EKeyCode::eF18: return "F18";
			case EKeyCode::eF19: return "F19";
			case EKeyCode::eF20: return "F20";
			case EKeyCode::eF21: return "F21";
			case EKeyCode::eF22: return "F22";
			case EKeyCode::eF23: return "F23";
			case EKeyCode::eF24: return "F24";
			case EKeyCode::eF25: return "F25";
			case EKeyCode::eKP0: return "Keypad 0";
			case EKeyCode::eKP1: return "Keypad 1";
			case EKeyCode::eKP2: return "Keypad 2";
			case EKeyCode::eKP3: return "Keypad 3";
			case EKeyCode::eKP4: return "Keypad 4";
			case EKeyCode::eKP5: return "Keypad 5";
			case EKeyCode::eKP6: return "Keypad 6";
			case EKeyCode::eKP7: return "Keypad 7";
			case EKeyCode::eKP8: return "Keypad 8";
			case EKeyCode::eKP9: return "Keypad 9";
			case EKeyCode::eKPDecimal: return "Keypad Decimal";
			case EKeyCode::eKPDivide: return "Keypad Divide";
			case EKeyCode::eKPMultiply: return "Keypad Multiply";
			case EKeyCode::eKPSubtract: return "Keypad Subtract";
			case EKeyCode::eKPAdd: return "Keypad Add";
			case EKeyCode::eKPEnter: return "Keypad Enter";
			case EKeyCode::eKPEqual: return "Keypad Equals";
			case EKeyCode::eLeftShift: return "Left Shift";
			case EKeyCode::eLeftControl: return "Left Control";
			case EKeyCode::eLeftAlt: return "Left Alt";
			case EKeyCode::eLeftSuper: return "Left Super";
			case EKeyCode::eRightShift: return "Right Shift";
			case EKeyCode::eRightControl: return "Right Control";
			case EKeyCode::eRightAlt: return "Right Alt";
			case EKeyCode::eRightSuper: return "Right Super";
			case EKeyCode::eMenu: return "Menu";
		}
		return "?Unknown Key?";
	}
}
